### ISSUE TITLE
linux crypto api issue

### ISSUE THREAD

**Issue by lktop** [landhb/DrawBridge#10]
Hello I saw that you have used the crypto api of Linux in your project. I saw that you used the crypto_akcipher_verify interface. May I ask if you have used other crypto_akcipher_encrypt and crypto_akcipher_decrypt api? I have a problem when using the public key for decryption
, Have you tried to decrypt successfully with the public key? 
Looking forward to your!

**Comment by landhb** [comment]
Hi, it should work very similarly, newer kernels actually use those methods inside the PKCS1 driver to do the verification.

May be worth looking at how they use that API:

https://github.com/torvalds/linux/commit/3ecc97259934489e7e03cbeb1d70f6a23cccb3ae
