### ISSUE TITLE
Kernel 5.x compatibility

### ISSUE THREAD

**Issue by ipersons** [landhb/DrawBridge#11]
There's a few issues currently blocking 5.x compatibility.

- [x] The Makefile is using a now [deprecated](https://patchwork.kernel.org/patch/10690487/) argument for out of tree module builds via kbuild.
- [x] The timekeeping functions were reworked in 5.6, moving to 64-bit even on 32-bit architectures to avoid the 2038 problem. This should also fix a bug where the rust client was always sending knocks with 64-bit timestamps, which a 32-bit kernel would not handle properly.
- [x] The sign/verify functionality of the rsa crypto backend was [removed](https://github.com/torvalds/linux/commit/3ecc97259934489e7e03cbeb1d70f6a23cccb3ae) in 5.2.

**Comment by landhb** [comment]
Fixed in #12, which resulted in ba8ef0895d2fff322beca31ac723fd468749a989
