### ISSUE TITLE
Concurrent requests crash

### ISSUE THREAD

**Issue by cppcoffee** [landhb/DrawBridge#34]
Using two `wget` concurrently downloading 256M+ files on unlock port, it crashes. on 32-core CPU machines.

Last message:

```
Message from vagrant at Nov 11 17:51:29 ...
kernel:Kernel panic - not syncing: Fatal exception in interrupt
```

kernel version:

```shell
# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

# uname -a
Linux vagrant 5.4.188-1.el7.elrepo.x86_64 #1 SMP Mon Mar 28 09:10:07 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by landhb** [comment]
@cppcoffee I think the #35 should fix this if you're able to test it out on your end as well. Thanks!

**Comment by cppcoffee** [comment]
Hi @landhb , https://github.com/landhb/DrawBridge/pull/39 using atomic operations on `time_updated` variable, fixed the problem, please review it.
