### ISSUE TITLE
init_keys always returns error.

### ISSUE THREAD

**Issue by LaurenIsACoder** [landhb/DrawBridge#4]
I'm currently developing a kernel module where I'm performing RSA signature verification. I found your answer on stackoverflow. 
The public_key always fails at init_keys, dmesg just prints: [!] Could not set the public key. Does dmesg mean the public_key  is wrong? How to set public_key  in kernel module ? Can you help me out?
Here is my public key:
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqPdPMzEYirodOYw/GoLyFUo547OBHm3O9/KpF6yoW9lqiDHGUF4Hs5pk/tTElSMh2o5wtM1zuehmJHtetnoV16Sko4Fx6C0VXxUqJyg8twKvC4Cj/nmFK4ARayn5AaJRhvIMq560mfh2UotyIL6Zsi+f9Z8usuDP8MWyhM9nZGQIDAQAB
-----END PUBLIC KEY-----

Thanks!

**Comment by landhb** [comment]
Your public key is likely in an incompatible format. Please reference [RFC 3447 where it outlines ASN.1 syntax for an RSA public key.](https://tools.ietf.org/html/rfc3447#page-44). In the DrawBridge readme there is a section that describes how to create a compatible key manually. Additionally the gen_keys.sh script will do it for you.

https://github.com/landhb/DrawBridge/blob/master/gen_keys.sh

**Comment by LaurenIsACoder** [comment]
I really appreciate it, the problem is solved.
